name: build
on: 
- pull_request
- push

jobs:
  build:
    strategy:
      matrix:
        java: 
        - 17
        os:
        - ubuntu-latest
        #-windows-2022
    runs-on: ${{ matrix.os }}
    steps:

    - name: setup node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/

    - name: setup jdk ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: checkout repository
      uses: actions/checkout@v4

    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: make gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew

    - name: build
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk${matrix.java}-${matrix.os}
        arguments: build
        gradle-version: wrapper

    - name: capture build artifacts
      if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/
